version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/bms_schema.sql:/docker-entrypoint-initdb.d/bms_schema.sql

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/bms
      JWT_SECRET: supersecretkey
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: .
    ports:
      - "4173:4173"
    depends_on:
      - backend

  odoo:
    image: odoo:16.0
    container_name: odoo
    depends_on:
      - db-odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db-odoo
      - USER=odoo
      - PASSWORD=odoo
    restart: always
    healthcheck:
      test: ["CMD", "python3", "-c", "import xmlrpc.client; xmlrpc.client.ServerProxy('http://localhost:8069/xmlrpc/2/common').list()"]
      interval: 10s
      timeout: 5s
      retries: 30

  db-odoo:
    image: postgres:15
    container_name: db-odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  middleware:
    build: ./middleware
    container_name: odoo-middleware
    depends_on:
      odoo:
        condition: service_healthy
    ports:
      - "4001:4001"
    environment:
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=odoo
      - ODOO_USER=admin
      - ODOO_PASSWORD=admin
    restart: always

  admin-frontend:
    build: ./admin-frontend
    container_name: admin-frontend
    ports:
      - "4174:5173" # Vite's default port is 5173
    depends_on:
      - middleware
    restart: always

volumes:
  db_data:
  odoo-data:
  odoo-db-data:
