version: '3.8'
services:
  odoo:
    image: odoo:16.0
    container_name: odoo
    depends_on:
      - db-odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db-odoo
      - USER=odoo
      - PASSWORD=odoo
    restart: always

  db-odoo:
    image: postgres:15
    container_name: db-odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  middleware:
    build: ../middleware
    container_name: odoo-middleware
    depends_on:
      - odoo
    ports:
      - "4001:4001"
    environment:
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=odoo
      - ODOO_USER=admin
      - ODOO_PASSWORD=admin
    restart: always

volumes:
  odoo-data:
  odoo-db-data:
